export const mockSearchContentItems = [
  {
    uri: 'test-uri-1',
    content: {
      type: 'workbook',
      luid: 'workbook-1-luid',
      title: 'Sales Dashboard',
      ownerName: 'John Doe',
      ownerId: 123,
      ownerEmail: 'john.doe@example.com',
      projectName: 'Finance',
      containerName: 'Finance',
      hitsTotal: 150,
      hitsSmallSpanTotal: 10,
      hitsMediumSpanTotal: 25,
      hitsLargeSpanTotal: 50,
      favoritesTotal: 5,
      modifiedTime: '2024-01-15T10:30:00Z',
      createdTime: '2023-12-01T09:00:00Z',
      tags: ['dashboard', 'sales'],
    },
  },
  {
    uri: 'test-uri-2',
    content: {
      type: 'datasource',
      luid: 'datasource-1-luid',
      title: 'Customer Data',
      ownerName: 'Jane Smith',
      ownerId: 456,
      ownerEmail: 'jane.smith@example.com',
      projectName: 'Marketing',
      containerName: 'Marketing',
      hitsTotal: 75,
      hitsSmallSpanTotal: 5,
      hitsMediumSpanTotal: 15,
      hitsLargeSpanTotal: 30,
      favoritesTotal: 3,
      modifiedTime: '2024-01-10T14:20:00Z',
      createdTime: '2023-11-15T11:30:00Z',
    },
  },
];
